---
- hosts: all
  sudo: True
  vars_files:
    - vars/main.yml

  environment:
    HTSLIB_DIR: "{{ ensembl_install_dir}}/htslib"

  roles:
    - { role: system, when: install_system is defined and install_system }
    - { role: desktop }
    - { role: chrome }
