---
- hosts: all
  sudo: True
  vars_files:
    - vars/main.yml

  environment:
    HTSLIB_DIR: "{{ ensembl_install_dir}}/htslib"
    PERL_RC: '/home/ensembl/.profile'

  roles:
    - { role: system, when: install_system is defined and install_system }
    - { role: plenv, perl_version: 5.14.4, become: false }
    - { role: desktop }
    - { role: chrome }
