---
- hosts: all
  sudo: True
  vars_files:
    - vars/main.yml
    - "{{ rest_private_dir }}/conf/release.yml"

  environment:
    HTSLIB_DIR: "{{ rest_install_dir}}/htslib"

  roles:
    - { role: system, when: install_system is defined and install_system }
    - { role: embassy, when: embassy_config is defined and embassy_config }
    - { role: ansible-perlbrew, perlbrew_user: "{{ rest_user }}", perl_version: perl-5.14.3, perlbrew_as: perl-5.14.3 }
    - { role: rest, become: false }
    - { role: rest_validate, become: false }
    - { role: rest_config, become: false }
