---
- hosts: all
  become: false
  vars_files:
    - vars/main.yml
    - "{{ rest_private_dir }}/conf/release_ebi.yml"

  vars:
    PERL_RC: "{{ ensembl_install_dir }}/activate_ensembl"
    HTTP_PROXY: http://hx-wwwcache.ebi.ac.uk:3128
    LANG: C
    SHARED_PATH: "/nfs/public/release/ensweb-software/sharedsw/e{{ ensembl_release }}"
    PROGRESSIVE_CACTUS_DIR: "{{ SHARED_PATH }}/paths/progressiveCactusFake/"
    install_my_own_hdf5: false
    install_progressivecactus: false
    vcf_config_json: vcf_config_ebi.json.j2
    ga_vcf_config_json: ga_vcf_config_ebi.json.j2
    validate_rest: true

  environment:
    HTSLIB_DIR: "{{ ensembl_install_dir}}/htslib"
    HTTP_PROXY: "{{ HTTP_PROXY }}"
    HTTPS_PROXY: "{{ HTTP_PROXY }}"
    http_proxy: "{{ HTTP_PROXY }}"
    https_proxy: "{{ HTTP_PROXY }}"

  roles:
    - { role: ebi_brew, become: false }
    - { role: plenv, perl_version: 5.14.4, plenv_install_dir: "{{ ensembl_install_dir }}/.plenv" }
    - { role: rest, become: false }
    - { role: rest_config, become: false }
    - { role: rest_validate, become: false, when: validate_rest|bool }
