---
- hosts: all
  become: false
  vars_files:
    - vars/main.yml
    - "{{ rest_private_dir }}/conf/release_ebi_common.yml"
    - "{{ rest_private_dir }}/conf/release_ebi_{{ deploy_conf | default('live') }}.yml"

  vars:
    PERL_RC: "{{ ensembl_install_dir }}/activate_ensembl"
    HTTP_PROXY: http://hx-wwwcache.ebi.ac.uk:3128
    LANG: C
    SHARED_PATH: "/nfs/public/release/ensweb-software/sharedsw/e{{ ensembl_release }}"
    PROGRESSIVE_CACTUS_DIR: "{{ SHARED_PATH }}/paths/progressiveCactusFake/"
    install_my_own_hdf5: false
    install_progressivecactus: false
    vcf_config_json: vcf_config_ebi.json.j2
    ga_vcf_config_json: ga_vcf_config_ebi.json.j2
    compara_halxs_makefile: Makefile-Linuxbrew.PL
    fix_catalyst_root_dir: true
    compara_halxs_compile: true

  environment:
    HTSLIB_DIR: "{{ ensembl_install_dir}}/htslib"
    HTTP_PROXY: "{{ HTTP_PROXY }}"
    HTTPS_PROXY: "{{ HTTP_PROXY }}"
    http_proxy: "{{ HTTP_PROXY }}"
    https_proxy: "{{ HTTP_PROXY }}"

  roles:
    - { role: ebi_brew, become: false }
    # - { role: plenv, perl_version: 5.26.1, plenv_install_dir: "{{ ensembl_install_dir }}/.plenv" }
    # - { role: rest, become: false }
    - { role: rest_config, become: false }
    # - { role: rest_config_fb, become: false, when: setup_fallback is defined and setup_fallback|bool }
    # - { role: rest_validate, become: false, when: validate_rest is defined and validate_rest|bool }
