# Add Mate desktop PPA
- name: Add Mate apt repo
  apt_repository:
    repo: 'ppa:ubuntu-mate-dev/xenial-mate'
  register: mate_ppa

- name: Refresh the apt cache
  apt:
    upgrade: dist
    update_cache: yes
  when: mate_ppa
  register: dist_upgraded

- name: Set MySQL root password before installing
  debconf: name='mysql-server-5.7' question='mysql-server/root_password' value='ensembl' vtype='password'
  register: mysql_passwd_set
  
- name: Confirm MySQL root password before installing
  debconf: name='mysql-server-5.7' question='mysql-server/root_password_again' value='ensembl' vtype='password'
  register: mysql_passwd_set_again

- name: Install common desktop packages
  action: apt pkg={{item}} state=installed
  with_items:
       - unzip
       - git
       - build-essential
       - zlib1g-dev
       - emacs24
       - libmysqlclient-dev
       - libxml2-dev
       - libexpat1-dev
       - libdbi-perl
       - libdbd-mysql
       - libdbd-mysql-perl
       - python-mysqldb
       - sqlite3
       - libmysqlclient-dev
       - mysql-server
       - emacs24
       - vim
       - python-gnomekeyring
       - chromium-browser
       - ubuntu-mate-core
  when: dist_upgraded and mysql_passwd_set and mysql_passwd_set_again
  register: desktop_pkgs_installed

- name: Clear the gnome keyring so no popup occurs
  shell: python -c "import gnomekeyring;gnomekeyring.change_password_sync('login', 'ensembl', '');"
  become: true
  become_user: "{{ ensembl_user }}"

- mysql_user:
    login_user: root
    login_password: ensembl
    name: travis
    priv: '*.*:ALL'
    state: present
  when: desktop_pkgs_installed

- name: Install Ensembl repos
  git: repo="{{ item.repo }}" dest="{{ ensembl_install_dir }}/{{ item.dir }}" version="{{ item.version | default(ensembl_repo_version) }}" clone=yes
  with_items:
       - { repo: 'https://github.com/Ensembl/ensembl-tools.git', dir: ensembl-tools }
       - { repo: 'https://github.com/Ensembl/ensembl-git-tools.git', dir: ensembl-git-tools, version: 'master' }
       - { repo: 'https://github.com/Ensembl/ensembl-hive.git', dir: ensembl-hive, version: 'master' }
  become: true
  become_user: "{{ ensembl_user }}"
  register: repos_exist

- name: Configure bashrc environment
  lineinfile: dest="{{ homedir }}/.bashrc" line="{{ item }}"
  with_items:
    - "# This MUST be set for LWP::Simple to retrieve cache files back from the Ensembl FTP site"
    - "export FTP_PASSIVE=1"
  become_user: "{{ ensembl_user }}"

- name: restore bind cfg symlink
  file: dest="{{ item.dest }}" src="{{ item.src }}" state=link mode=0755 force=yes
  with_items:
    - { dest: "{{ homedir }}/VEP", src: "{{ ensembl_install_dir }}/ensembl-tools/scripts/variant_effect_predictor/" }
    - { dest: "{{ homedir }}/Desktop/ensembl-api-folder", src: "{{ ensembl_install_dir }}/" }
    - { dest: "{{ homedir }}/verify_installation", src: "{{ ensembl_install_dir }}/ensembl/misc-scripts/ping_ensembl.pl" }

- name: Install the e! background
  copy: src={{role_path}}/files/ebang-1440-900.png dest=/usr/share/backgrounds/warty-final-ubuntu.png owner=root group=root mode=0644

- name: Fix locale for gnome-terminal
  shell: "{{ item }}"
  with_items:
    - "locale-gen"
    - 'localectl set-locale LANG="en_US.UTF-8"'
  become: true
  become_user: root

- name: create auto-login config directory
  file: path="/etc/lightdm/lightdm.conf.d" state=directory mode=0755 force=yes
  register: lightdm_dir_made
  
- name: Set auto-login ensembl user
  blockinfile:
    dest: "/etc/lightdm/lightdm.conf.d/50-login.conf"
    create: yes
    owner: root
    mode: 0644
    block: |
      [SeatDefaults]
      autologin-user=ensembl
  when: lightdm_dir_made

- name: Disable screen locking and make desktop icons
  copy: src="{{ item.src }}" dest="{{ item.dest }}" owner="{{ ensembl_user }}" mode=0755
  with_items:
    - { src: "{{role_path}}/files/lock_disable.sh", dest: "/home/lock_disable.sh" }
    - { src: "{{role_path}}/files/lock_disable.sh.desktop", dest: "/etc/xdg/autostart/lock_disable.sh.desktop" }
    - { src: "{{role_path}}/files/google-chrome.desktop", dest: "{{ homedir }}/Desktop/google-chrome.desktop" }
    - { src: "{{role_path}}/files/VEP.desktop", dest: "{{ homedir }}/Desktop/VEP.desktop" }

- name: Remove Amazon search results icon
  file: path=/usr/share/applications/ubuntu-amazon-default.desktop state=absent force=yes
