# Role: rest_ebi_config

- name: Create local copy of REST configs
  local_action: template src="{{ item.src }}" dest="{{ item.dest }}" mode=0640
  with_items:
    - { src: "{{ rest_private_dir }}/conf/ensembl_rest.conf.j2", dest: "{{ rest_private_dir }}/conf/ensembl_rest.conf" }
    - { src: "{{ rest_private_dir }}/conf/ensrest.psgi.j2", dest: "{{ rest_private_dir }}/conf/ensrest.psgi" }
    - { src: "{{ rest_private_dir }}/conf/ga_references.json.j2", dest: "{{ rest_private_dir }}/conf/ga_references_GRCh{{ ensembl_sub_release }}.json" }
    - { src: "{{ rest_private_dir }}/conf/vcf_config.json.j2", dest: "{{ rest_private_dir }}/conf/vcf_config.json" }
    - { src: "{{ rest_private_dir }}/conf/vep_plugin_config.txt.j2", dest: "{{ rest_private_dir }}/conf/vep_plugin_config.txt" }
#  when: release_loaded

- name: Deploying REST configs
  template: src="{{ item.src }}" dest="{{ item.dest }}" mode=0640
  with_items:
    - { src: "{{ rest_private_dir }}/conf/ensembl_rest.conf.j2", dest: "{{ ensembl_install_dir }}/ensembl-rest/configurations/production/ensembl_rest.conf" }
    - { src: "{{ rest_private_dir }}/conf/ensrest.psgi.j2", dest: "{{ ensembl_install_dir }}/ensembl-rest/configurations/production/ensrest.psgi" }
    - { src: "{{ rest_private_dir }}/conf/ga_references.json.j2", dest: "{{ ga4gh_reference_config }}" }
    - { src: "{{ rest_private_dir }}/conf/vcf_config_ebi.json.j2", dest: "{{ vcf_config }}" }
    - { src: "{{ rest_private_dir }}/conf/vep_plugin_config.txt.j2", dest: "{{ vep_plugin_config }}" }
#  when: release_loaded

- name: Copy non-templated REST config files
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0640
  with_items:
    - { src: "{{ rest_private_dir }}/conf/ga_vcf_config_GRCh{{ ensembl_sub_release }}.json", dest: "{{ ga4gh_config }}" }

- name: Add perl env variables to startup script
  blockinfile:
    path: "{{ ensembl_install_dir }}/ensembl-rest/bin/production/start_rest_server.sh"
    marker: "# {mark} Ansible Perl Paths"
    content: |
    source {{ PERL_RC | default('~/.bashrc') }}
       
- debug:
    msg: "vep_cache_dir: {{ vep_cache_dir }}"
#  when: release_loaded
