- name: Install common system packages
  action: apt pkg={{item}} state=installed
  with_items:
       - unzip
       - git
       - build-essential
       - zlib1g-dev
       - emacs24
       - libmysqlclient-dev
       - libxml2-dev
       - libexpat1-dev
       - liblzma-dev
       - libbz2-dev
