# role: system

- name: Install common system packages (common)
  action: apt pkg={{item}} state=installed
  with_items:
       - unzip
       - git

- name: Install common system packages (Debian)
  action: apt pkg={{item}} state=installed
  with_items:
       - build-essential
       - zlib1g-dev
       - emacs24
       - libmysqlclient-dev
       - libxml2-dev
       - libexpat1-dev
       - liblzma-dev
       - libbz2-dev
       - python-pip
       - virtualenv
  when: ansible_os_family == 'Debian'

# Not yet tested on a RH based system
- name: Install common system packages (RedHat)
  action: apt pkg={{item}} state=installed
  with_items:
       - gcc
       - gcc-c++
       - make
       - zlib-devel
       - emacs-24
       - mysql-devel
       - libxml2-devel
       - libexpat1-devel
       - liblzma-devel
       - libbz2-devel
       - python-pip
       - python-virtualenv
  when: ansible_os_family == 'RedHat'

# Deal with an ubuntu specific bug with perl
- name: Correct Ubuntu python bug
  shell: ln -sf /usr/lib/python2.7/plat-*/_sysconfigdata_nd.py /usr/lib/python2.7/
  when: ansible_distribution == 'Ubuntu'
