# Role: rest/comparahal

- name: Read the Compara HAL XS Makefile.PL
  shell: cat {{ ensembl_install_dir }}/ensembl-compara/modules/Bio/EnsEMBL/Compara/HAL/HALXS/Makefile.PL
  register: HAL_Makefile

- name: Make the Compara progressiveCactus HAL XS bindings, old way
  shell: ". {{ PERL_RC | default('~/.bashrc') }} && perl Makefile.PL && make"
  args:
    chdir: "{{ ensembl_install_dir }}/ensembl-compara/modules/Bio/EnsEMBL/Compara/HAL/HALXS"
  when: HAL_Makefile.stdout.find('PROGRESSIVE_CACTUS_DIR') != -1

- name: Make the Compara progressiveCactus HAL XS bindings, new way
  shell: ". {{ PERL_RC | default('~/.bashrc') }} && perl Makefile.PL {{ PROGRESSIVE_CACTUS_DIR | default(PROGRESSIVE_CACTUS_DEFAULT) }}/hdf5 {{ PROGRESSIVE_CACTUS_DIR | default(PROGRESSIVE_CACTUS_DEFAULT) }}/sonlib {{ PROGRESSIVE_CACTUS_DIR | default(PROGRESSIVE_CACTUS_DEFAULT) }} hal && make"
  args:
    chdir: "{{ ensembl_install_dir }}/ensembl-compara/modules/Bio/EnsEMBL/Compara/HAL/HALXS"
  when: HAL_Makefile.stdout.find('Need to run this makefile with 3 paths') != -1

