- name: Create REST install directory
  file: path="{{ item }}" state=directory mode=0755 owner="{{ ensembl_user }}" group="{{ ensembl_group }}"
  with_items:
    - "{{ ensembl_install_dir }}"
    - "{{ logdir }}"
  register: rest_dir_exists

- name: Install Ensembl repos
  git: repo="{{ item.repo }}" dest="{{ ensembl_install_dir }}/{{ item.dir }}" version="{{ item.version | default(ensembl_repo_version) }}" clone=yes
  with_items:
       - { repo: 'https://github.com/Ensembl/ensembl-rest.git', dir: ensembl-rest, version: 'master' }
       - { repo: 'https://github.com/Ensembl/ensembl-hdf5.git', dir: ensembl-hdf5, version: 'master' }
  when: rest_dir_exists
  register: repos_exist

- name: Install repo cpan dependencies
  command: "sudo -iu {{ ensembl_user }} cpanm -v --installdeps --with-recommends --notest --cpanfile={{ ensembl_install_dir }}/{{ item }}/cpanfile ."
  args:
    chdir="{{ ensembl_install_dir }}/{{ item }}"
  with_items:
       - ensembl-rest
  when: repos_exist
